version: '2'
services:
    web:
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile-prod
        container_name: [projectname]_web_prod
        volumes:
            - /var/www/html/typo3conf
        environment:
            DMK_APP_ENV: 'PRODUCTION'
            
