FROM ###username###/typo3base:7.6


COPY ./sources /var/www/html
COPY ./scripts/entrypoint.sh /

WORKDIR /var/www/html

#set oauth token for github
RUN composer.phar config -g github-oauth.github.com $github_oauth;

#run composer to build new TYPO3 project
#RUN composer.phar update --prefer-stable --prefer-source && touch FIRST_INSTALL

#problems with local mounted volumes and user rights
#RUN chown -R www-data:www-data /var/www
#USER www-data

CMD ["/entrypoint.sh"]
