version: '2'
services:
    web:
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile-install
        container_name: ###projectname###_web_local
        volumes:
            - './sources:/var/www/html/'
        environment:
            DMK_APP_ENV: 'LOCAL'
            
