FROM grisuu/typo3base:7.6

#USER www-data

COPY ./sources /var/www/html/
COPY ./scripts/entrypoint.sh /

#noetig um Probleme mit de, owner des Hostsystems zu umgehen. TODO: uid des Hostsystems als ARG uebergeben
#RUN usermod -u $user_id www-data && groupmod -g $group_id www-data
#RUN chown -R www-data:www-data /var/www

WORKDIR /var/www/html

#run composer to build new TYPO3 project
RUN composer.phar update --prefer-stable --prefer-source -o --no-dev

RUN mv .htaccess_prod .htaccess && chown -R www-data:www-data /var/www/html
CMD ["/entrypoint.sh"]
