FROM pluto:5000/grisuu/typo3base:7.6


COPY ./sources /var/www/html
COPY ./scripts/entrypoint.sh /

WORKDIR /var/www/html

#run composer to build new TYPO3 project
#RUN composer.phar update --prefer-stable --prefer-source && touch FIRST_INSTALL

#problems with local mounted volumes and user rights
#RUN chown -R www-data:www-data /var/www
#USER www-data

CMD ["/entrypoint.sh"]
