FROM pluto:5000/grisuu/typo3base:7.6

#USER www-data

COPY ./sources /var/www/html/
COPY ./scripts/entrypoint.sh /

WORKDIR /var/www/html

#run composer to build new TYPO3 project
RUN composer.phar update --prefer-stable --prefer-source -o --no-dev

RUN mv .htaccess_prod .htaccess && chown -R www-data:www-data /var/www/html
CMD ["/entrypoint.sh"]
